### ISSUE TITLE
elexpander tracking github workflow

### ISSUE THREAD

**Issue by elexpander** [githubteacher/sep-26-everyone#10]
# elexpander tracking github workflow
- [x] Create a branch
- [x] Add commits on branch
- [ ] Open pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
