### ISSUE TITLE
Alphafounder tracking GitHub workflow

### ISSUE THREAD

**Issue by r-brink** [githubteacher/sep-26-everyone#12]
# Alphafounder tracking GitHub workflow
- [x] Create a branch
- [x] Add commits on branch
- [x] Open pull request
- [x] Collaborate/more commits
- [x] Merge pull request

**Comment by Alphafounder** [comment]
- [ ] Create a branch
- [ ] Add commits on branch
- [ ] Open pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
