### ISSUE TITLE
mindhyani tracking github workflow

### ISSUE THREAD

**Issue by mindhyani** [githubteacher/sep-26-everyone#13]
# mindhyani tracking github workflow
- [ ] Create a branch
- [ ] Add commits on branch
- [ ] Open pull request
- [ ] collaborate/more commits
- [ ] Merge pull request

**Comment by mindhyani** [comment]
my issue is "Very Important" :lollipop:
