### ISSUE TITLE
linuxandsarcasm tracking GitHub workflow

### ISSUE THREAD

**Issue by linuxandsarcasm** [githubteacher/sep-26-everyone#16]
## linuxandsarcasm tracking GitHub workflow 🐕
- [x] Create a branch
- [x] add commits on branch
- [x] open a pull request
- [ ] collaborate/more commits
- [x] merge pull request
