### ISSUE TITLE
iamdv tracking GitHub workflow

### ISSUE THREAD

**Issue by iamdv** [githubteacher/sep-26-everyone#17]
# @iamdv tracking GitHub Workflow :apple:
- [x] Create a branch
- [x] Add commits on branch
- [x] Open pull request
- [ ] Colloborate/more commits
- [ ] Merge pull request

**Comment by iamdv** [comment]
Added a branch

**Comment by iamdv** [comment]
Added commits to my branch

**Comment by iamdv** [comment]
Opened pull request
