### ISSUE TITLE
jurajsucik tracking GitHub workflow

### ISSUE THREAD

**Issue by jurajsucik** [githubteacher/sep-26-everyone#20]
# jurajsucik tracking GitHub workflow
- [x] create a branch
- [x] add commits on branch
- [x] open pull request
- [x] collaborate/more commits
- [x] merge pull requests
