### ISSUE TITLE
LauraU tracking Github workflow

### ISSUE THREAD

**Issue by laurauzcategui** [githubteacher/sep-26-everyone#5]
# Laura tracking Github Workflow
- [x] Try to be quick 
- [x] Post the issue 
- [ ] Visit my repo [laurauzcategui](www.github.com/laurauzcategui)

🐶  
- [x] Create a branch
- [x] Add commits on branch
- [x] Open pull request
- [ ] Collaborate/more commits
- [ ] Merge pull request
