### ISSUE TITLE
alexinseattle tracking GitHub workflow

### ISSUE THREAD

**Issue by alexinseattle** [githubteacher/sep-26-everyone#8]
# alexinseattle tracking GitHub workflow
- bullets
  🍵 
  🐱 
  🐕 
- [] Create a branch
  -[] Add commits on branch
- [] Open pull request
- [] Collaborate/more commits
- [] Merge pull request
