### ISSUE TITLE
Christanya tracking GitHub workflow

### ISSUE THREAD

**Issue by Christanya** [githubteacher/sep-26-everyone#9]
# Christanya tracking GitHub workflow
- [x] Create a branch
- [x] Add commits on branch
- [x] Open pull request
- [x] Collaborate / more commits
- [ ] Merge pull request
